apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: acnbx5v67-dotnet-basic
  janus-idp.io/tekton: acnbx5v67-dotnet-basic
  backstage.io/kubernetes-id: acnbx5v67-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: acnbx5v67-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
